---
  - name: 'Create mysql database'
    mysql_db:
      name: '{{ wp_db_name }}'
      state: present
  
  - name: 'Create user and grant permission'
    mysql_user:
      name: '{{ wp_db_user }}'
      password: '{{ wp_db_password }}'
      host: localhost
      priv: '{{ wp_db_name }}.*:ALL'
      state: present